# Generated by Django 4.2.15 on 2024-09-03 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('resturant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('customeuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('res_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resturant.resturant')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.customeuser',),
        ),
    ]
