# Generated by Django 4.2.15 on 2024-09-03 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0001_initial'),
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='adminforignkey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminn.adminn'),
        ),
    ]
