# Generated by Django 4.2.15 on 2024-09-03 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0001_initial'),
        ('owner', '0002_owner_adminforignkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='res_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resturant.resturant'),
        ),
    ]
