# Generated by Django 4.2.15 on 2024-09-03 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resturant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=60)),
                ('res_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resturant.resturant')),
            ],
        ),
    ]
